### ISSUE TITLE
Cant make it work on Windows or Mac

### ISSUE THREAD

**Issue by ed-sparkes** [mulesoft/api-console#539] opened 2017-11-09 09:11 UTC
Hi having some issues with this ...

On Windows - Cannot find module api-console-cli-build 

So i tried on mac ....

hundreds of bower errors ....

 invalid-meta The "main" field cannot contain minified files

invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["json-viewer.html","js-max-number-error.html"]

eventually ending in ....

error:
error: Maximum call stack size exceeded
error: RangeError: Maximum call stack size exceeded
    at Function.makeConsistent (/usr/local/lib/node_modules/api-console-cli/node_modules/raml2obj/lib/consistency-helpers.js:61:38)
    at obj.forEach (/usr/local/lib/node_modules/api-console-cli/node_modules/raml2obj/lib/consistency-helpers.js:52:36)
    at Array.forEach (native)
    at Function.makeConsistent (/usr/local/lib/node_modules/api-console-cli/node_modules/raml2obj/lib/consistency-helpers.js:51:11)
    at keys.forEach (/usr/local/lib/node_modules/api-console-cli/node_modules/raml2obj/lib/consistency-helpers.js:70:38)

Any help greatly appreciated.

**Comment by jarrodek** [comment] 2017-11-10 21:11
Hi,
Bower error can be ignored. It's just the components that builds the console aren't very strict about bower file structure.

As for the missing module on windows - I am still working on this issue. It is a duplicate of #538

As for the maximum call stack size - it's a known issue with datatype expansion library in very specific cases of RAML input. We are working to resolve this issue.

**Comment by jarrodek** [comment] 2020-01-16 20:53
This is now fixed in version 6.0.0 and api-console-cli 2.0.0

**Closed by jarrodek** 2020-01-16 20:53 UTC
