### ISSUE TITLE
RAML 1.0 array types not working

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#300] opened 2016-06-21 09:36 UTC
The following example does not work with the current version (master) of the API Console.

``` yaml
#%RAML 1.0
title: Array does not work API
version: 1.0
mediaType:  application/json

types:
  ORX_ARRAY:
    type: array
    items: string
    minItems: 1



/cmt:
  get:
    queryParameters:
      details:
        displayName: details
        type: string
        required: false
      modemCount:
        displayName: modemCount
        type: string
        required: false
      orx:
        description: List ORX type.
        type: ORX_ARRAY
        required: false
    responses:
      200:
        body:
          application/json:
```

First the following is what I get when trying to provide information inside the console:

![image](https://cloud.githubusercontent.com/assets/498114/16224844/cccbe422-379b-11e6-8bf2-37b40c30300b.png)

I am providing a single string and get invalid type. Putting the string into quotes lets the error message disappear. Providing an array like `[ "hello", "world" ]` I get the following response:

``` json
{
  "error": "query parameters: orx: unknown type string[]"
}
```

**Comment by juancoen** [comment] 2016-06-21 15:23
For `string[]`, Console expects a JSON string for an array, so the one you provided (`[ "hello", "world" ]`) is OK. As for the response, it depends on the service that Console is hitting when using the Try It, so it's not a Console issue.

**Comment by sichvoge** [comment] 2016-06-21 16:15
@juancoen thanks for your response. I understand that this might be a problem on the mocking service that I have enabled but what about the issue that using `sdfsfdgd` vs `"sdfsfdgd"` actually gives me to different validation results? The former being invalid and the latter valid.

**Comment by juancoen** [comment] 2016-06-21 16:29
yeah, that seems like a Console bug

**Comment by sichvoge** [comment] 2016-07-15 10:50
@juancoen did you had a chance to fix the console issue?

> what about the issue that using sdfsfdgd vs "sdfsfdgd" actually gives me to different validation results? The former being invalid and the latter valid

**Comment by sichvoge** [comment] 2017-03-23 16:46
No, I am even getting an "invalid type" for `["hello", "world"]`.

**Comment by carowright** [comment] 2017-05-19 13:06
Fix available in [v3.0.17](https://github.com/mulesoft/api-console/releases/tag/v3.0.17)

**Comment by augonzaleztek** [comment] 2017-05-24 22:02
Hi, 
The issue is not completely solved. In next release v3.0.17 the problem is that if you try to use a parameter of type array but set REQUIRED:true or do not set REQUIRED, the execution in console will fail. 
As a workaround set REQUIRED:false

**Comment by sichvoge** [comment] 2017-05-25 08:32
@augonzaleztek should we reopen this ticket and make sure we fix this issue?

**Comment by sichvoge** [comment] 2017-06-26 08:47
This is very elegantly solved in the new API console version v4. :)

![image](https://user-images.githubusercontent.com/498114/27531426-752bfd24-5a54-11e7-9f5d-37957d2d2ba0.png)

**Comment by jarrodek** [comment] 2017-06-27 17:08
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c

**Closed by jarrodek** 2017-06-27 17:08 UTC
Labels: bug, major, raml1.0, resolved, v4
