### ISSUE TITLE
validation error in console but not designer

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#307] opened 2016-07-28 10:57 UTC
Not sure what the differences are but the console shows me a validation error that "node example can not be a scalar", but there is no error in the designer.

![image](https://cloud.githubusercontent.com/assets/498114/17210363/67f684d0-54ba-11e6-9dab-5e2a4ecebd84.png)

**Comment by sichvoge** [comment] 2016-07-28 10:58
OK it seems that the validation field does not update if you change the content. I had to reload the page again and copy & paste the content

**Comment by nmarinel01** [comment] 2017-03-03 16:12
Hi @sichvoge !
Im closing this report since I could not reproduce this behavior. This issue seems not to be present at v3.0.13 of Console.
Please, reopen if necessary.
Regards

**Closed by nmarinel01** 2017-03-03 16:12 UTC
Labels: bug, minor
