### ISSUE TITLE
Can't include colons in HTTP headers via 'Try It'

### ISSUE THREAD

**Issue by bmarchbank** [mulesoft/api-console#557] opened 2018-02-26 12:30 UTC
When making a request using the 'Try It' functionality, the HTTP header values are stripped after this first colon.

## Steps to reproduce
1. Submit a request with, for example, an RFC-3339 date-time string as a header value (`2018-01-01T00:00:00.000Z`)
2. View the value in the back-end

## Expected result
The header value is `2018-01-01T00:00:00.000Z`

## Actual result
The header value is `2018-01-01T00`

## Was this working before?

- [ ] Yes, it was working before
- [ ] No, it was already broken
- [x] I don't know / not sure

## Affected browsers

- [x] All or I don't know
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer <\3
- [ ] Edge
- [ ] Safari
- [ ] Other (please, specify)

**Comment by jarrodek** [comment] 2018-02-28 05:34
Thank you for the issue report.
Is this happening in version 4 or 3 of the API console?

**Comment by bmarchbank** [comment] 2018-02-28 12:09
@jarrodek version 3.0.17

**Comment by carowright** [comment] 2018-03-05 20:53
Hi @bmarchbank !
Thanks for reporting. Could you please attach a small example in order to reproduce this?

Thank you!

**Comment by bmarchbank** [comment] 2018-03-09 12:54
Hi @carowright  ,

Sorry for the slow response.  I've attached a basic example below (see README).  Also, @jarrodek ,  I think I was looking at the wrong package when I said version 3, I think it's actually version 4?

[header-example.zip](https://github.com/mulesoft/api-console/files/1796939/header-example.zip)

Thanks.

**Comment by jarrodek** [comment] 2018-03-10 03:26
@carowright Since it's v4 related I will handle it.
@bmarchbank thank you for reporting. I am currently rewiring this module. If I reproduce the issue I will patch it.

**Comment by jarrodek** [comment] 2019-12-12 21:50
This issue is fixed in API Console version 6. The release is planned very soon.

**Closed by jarrodek** 2019-12-12 21:50 UTC
Labels: v4
