### ISSUE TITLE
Content of the 'tryit' action form is not memorized 

### ISSUE THREAD

**Issue by maryoush** [mulesoft/api-console#110] opened 2015-02-24 09:46 UTC
Hi,
the 'tryit' functionality seems to be very inconvenient to work with.
In some non trivial scenarios (consisting of more requests), every time you change the action for given resource the content (form) is completely re-setted (to defaults or given examples).
So next time you enter it you are forced to fill it in again - extremely inefficient.

I think this would be even nicer to keep the content for all adjusted actions for given end point (across many resources) - so one can just navigate through it.

Regards Mariusz.

**Comment by usarid** [comment] 2015-02-26 18:07
Mariusz, can you please say in detail what kind of change you would expect the contents to be preserved through? I'm not sure what you mean by "change the action".

**Comment by maryoush** [comment] 2015-02-26 23:10
Hi,
sorry for my clumsy explanation.
Imagine the scenario when you want to present couple of different calls on different endpoint for actions with specific for each set of query, header parameters and different body payloads, maybe some of them you want to repeat like eg. Gets to check the result.
As you navigate  through out the API console and enter some input for a Get action on endpoint /products, now you go to Post for the same endpoint /products to add some ( you provide some custom header + body payload) data and when you return back to the Get all entered input data eg. headers , query params + any custom ones are reset to the defaults. Following if you would like to go back again to Post to see what you sent as payload this is again reset to defaults.
Does this ring the bell ?
Sent from iPad

Dnia 26 lut 2015 o godz. 19:07 Uri Sarid <notifications@github.com> napisał(a):

**Comment by monami555** [comment] 2015-02-27 13:56
I believe it is basically about not clearing (or resetting) the input fields while switching between forms for different HTTP methods (HTTP actions) in the "Try it" section - like was happening in the older version on API Console. Not sure if before this functionality was intended, but it was extremely useful. Would be awesome if this could be brought back.

**Comment by meeque** [comment] 2015-06-02 09:27
Any news on this one? I think the described problem remains present; in 2.0.1 at least.

**Comment by marekasf** [comment] 2015-06-26 10:38
Do you have any plans to fix it?

**Comment by sichvoge** [comment] 2015-06-26 11:50
It's on the watch list @marekasf ;)

**Comment by kamkor** [comment] 2015-07-20 07:28
I would also appreciate a fix. Any updates?

**Comment by jarrodek** [comment] 2017-06-26 15:06
The v4 still doesn't support this as described in the issue. It preserves authorisation information across endpoints but other parameters are not stored and default values are inserted when displaying the request.

It can be managed in the request panel level to cache the results when changes and once the method is changed to restore that from the cache or use passed RAML data. However it would require few general changes in the element's architecture and it can't be fixed before v4 release. But because it's very interesting use case I will included it to the todo list and you may expect it to be resolved in coming weeks.

**Comment by jarrodek** [comment] 2020-01-16 21:31
Version 5 introduced values caching in the request editor.

**Closed by jarrodek** 2020-01-16 21:31 UTC
Labels: enhancement, v4, verified
