### ISSUE TITLE
message for required headers is not visible

### ISSUE THREAD

**Issue by carobazan** [mulesoft/api-console#506] opened 2017-07-20 19:46 UTC
Check attached image, message stating that headers are required is not completely visible in console

![screen shot 2017-07-20 at 4 42 33 pm](https://user-images.githubusercontent.com/22245749/28435790-e9e5bfaa-6d6a-11e7-880e-9a0d50d145ea.png)

**Comment by jarrodek** [comment] 2017-07-20 20:31
Please, consult this with Mulesoft design team. The element works as intended according to Mulesoft's components development guidelines.

**Comment by jarrodek** [comment] 2020-01-16 20:58
This was fixed in 5

**Closed by jarrodek** 2020-01-16 20:58 UTC
Labels: Anypoint, WAI
