### ISSUE TITLE
Bower install dependencies will complain

### ISSUE THREAD

**Issue by lanmolsz** [mulesoft/api-console#565] opened 2018-03-21 10:42 UTC
version: 4.2.0
error log: ECONFLICT Unable to find suitable version for raml-json-enhance

**Comment by jarrodek** [comment] 2018-03-23 17:13
Yesterday I was building the console and it was OK. I just rebuild it again on different OS and it also worked.
If you have old `bower_components` directory please remove it as it may contain some dependencies that bower can't handle:

```
rm -rf bower_components/
bower i
```
If this won't help, use `bower cache clean` to clean the cache.

I am closing this as I can't reproduce.

P.S.
This year we are going to move from bower do node. It will be easier to manage dependencies there. However it requires a lot of work to upgrade the components to v1 spec of web components.
Stay tuned.

**Closed by jarrodek** 2018-03-23 17:13 UTC
