### ISSUE TITLE
Duplicated examples

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft/api-console#513] opened 2017-08-04 20:56 UTC
When using the following raml 

```
#%RAML 1.0
---
title: La Liga
version: 2.0
baseUri: http://localhost:8080/api
types:
  team: !include schemas/team.raml

/teams:
  displayName: Teams
  #description: |
  #  A collection of teams that are participating in La Liga. Teams API allow you add, remove and retrieve individual team information from La Liga.
  get:
    description: Obtain information from a collection of teams simultaneously
    queryParameters:
      city:
        description: |
          Filter the list of teams by home city.
        type: string
        required: false
        example: Barcelona
    responses:
      200:
        body:
          application/json:
            type: team []
            #example: !include examples/team-array-example.raml
  post:
    description: Add a new team to the league
    body:
      application/json:
        type: team
        example: !include examples/team-object-example.raml
    responses:
      201:
        description: |
          The team has been succesfully created
        headers:
          Location:
            type: string
            description: Location of the newly created team
      409:
        description: |
          The team already exists
```
team-object-example.raml

```
#%RAML 1.0 NamedExample

  name: Barcelona
  id: BAR
  homeCity: Barcelona
  stadium: Camp Nou
```
The console displays duplicated examples
<img width="1103" alt="screen shot 2017-08-04 at 5 55 48 pm" src="https://user-images.githubusercontent.com/5630419/28986641-349a3a56-793e-11e7-8562-8ad71ceec878.png">

Team type definition

```
#%RAML 1.0 DataType
type: teamPatch
properties:
  name:
    type: string
    description: Name of the team
  id:
    description: A three-letter code that identifies the team id
    type: string
    maxLength: 3
    minLength: 3
  homeCity:
   description: Name of the city to which this team belongs
   type: string
   required: false
  stadium:
   description: Name of the stadium
   type: string
example:
  name: "Barcelona"
  id: "BAR"
  homeCity: "Barcelona"
  stadium: "Camp Nou" 
```

**Comment by jarrodek** [comment] 2017-08-14 17:59
In type definition should it inherit from object?
Please, provide [minimal working example](https://en.wikipedia.org/wiki/Minimal_Working_Example) in the issues reports so it would be easier to reproduce and test.

Thanks.

**Comment by jarrodek** [comment] 2017-08-14 18:03
This is an issue with https://github.com/advanced-rest-client/raml2obj module.

**Comment by jarrodek** [comment] 2017-08-14 18:08
After recognizing the problem I'm closing it as WAI.

There's an issue with the RAML definition and not the console. Console is doing what it suppose to do. It merges examples from a type definition with inlined examples in the method definition. This was requested earlier by other users and this behavior make sense. This way you will not loose information from a fragment (data type) and still have information from the main api file definition.

**Closed by jarrodek** 2017-08-14 18:08 UTC
Labels: minor, v4

**Comment by marcadella** [comment] 2019-04-25 07:24
Hi, I disagree with your interpretation of the spec.
The spec talks about merging collections (https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#resource-types-and-traits-effect-on-collections) but that does only apply to traits and resource types! Furthermore node **example** is not a collection (**examples** is).
When Eleonora writes:
```
type: team
example: !include examples/team-object-example.raml
```
, she does an object type specialization (https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#object-type-specialization) and the spec clearly says that all the properties are overriden. There is no mention to merging.

The spec is right and there are tons of use cases where the merging behavior is clearly not desired.
For example if I define a type to represent an error (such as JSON API Error) and I use it everywhere with an example for each response returning an error, in the generated spec, I get all the examples for every single failed response. You understand that the documentation becomes useless.

**Comment by jarrodek** [comment] 2019-04-25 21:19
@jstoiko can you please take a look into this?

My POV is that the spec does not cover this case properly. I would expect that `NamedExample` fragment should be allowed as a value for `example` property.

Version 3 of AMF parser supports this as expected (example is included into the model) but version 4 (currently in preview) will ignore any `NamedExample` included into `example` property. 
I think next version of RAML should cover this issue and explicitly allow to include `NamedExample` to an `example` property (although I wouldn't be calling the fragment NamedExample anymore as there's no name in this case).

@marcadella The body declaration is not a type (as defined in RAML spec).  In the following code:

```yaml
application/json:
   type: team
   example: !include examples/team-object-example.raml
```
the body does not create a new type from `team` and overrides the `example` because it is defined in here. Instead it uses all properties defined in type fragment and adds other properties defined in the body definition. It does not override properties. @jstoiko please correct me if I'm wrong.

**Comment by jstoiko** [comment] 2019-04-25 22:54
First off, let me clarify the `NamedExample` issue. Two things:
- a `NameExample` fragment is described as follows: `A declaration of the examples facet, whose key is a name of an example and whose value describes the example`[1]
- as a result, a `NameExample` fragment may be `!include`d as value of `examples` (plural) NOT `example` (singular)

This means that the RAML snippet above is invalid to begin with. I could stop here but for the sake of the argument, let's say we were to make it valid, I see two ways to go about it:
1. rename `example:` to `examples:` and make sure the `!include`d `NamedExample` contains at least one named-example key as defined in the Spec[2]
2. remove the `#%RAML 1.0 NamedExample` header from the `!include`d example and rename that same file's extension from `.raml` to `.yaml`

That being said, whether using `example` or `examples`, there is no object type specialization happening here. "Object Type Specialization"[3] refers to the addition of properties to an object parent type that is inheriting the properties of another object type. I see no properties under `type: team`.

Although "User-defined facets" explicitly prohibits re-defining "facet names of any ancestor type"[4], RAML 1.0 does not prohibit re-defining built-in facets of parent types, at least not for example(s). That being said, both JSON and YAML 1.2 -- which RAML 1.0 is based on -- explicitly forbid duplicate keys in mappings. Because the resolution of the inheritance would result in having two example(s) facet, the only possible solution is for processors to **override** any parent type built-in facets. This means that in our scenario above, the example(s) of a type would override the example(s) of the parent type.

[1] https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#typed-fragments
[2] https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#defining-examples-in-raml
[3] https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#object-type-specialization
[4] https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#user-defined-facets
