### ISSUE TITLE
Cannot find module ... api-console-cli-build

### ISSUE THREAD

**Issue by valentin78** [mulesoft/api-console#537] opened 2017-10-26 08:53 UTC
i made following steps:
- npm install -g api-console-cli
- api-console build doc.raml

got error:
Error: Cannot find module '... \api-console-cli-build'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by jarrodek** [comment] 2017-10-28 22:58
Thank you issue report. It looks like a duplicate of https://github.com/mulesoft-labs/api-console-cli/issues/12 so I'll close it here.

**Closed by jarrodek** 2017-10-28 22:58 UTC
