### ISSUE TITLE
Layout breaks with long text

### ISSUE THREAD

**Issue by matart15** [mulesoft/api-console#306] opened 2016-07-28 10:17 UTC
Layout breaks with long text
![screen shot 2016-07-28 at 7 15 18 pm](https://cloud.githubusercontent.com/assets/17027219/17209397/cd54a40a-54f7-11e6-8be6-e8216c7d9e37.png)

**Comment by ibnesayeed** [comment] 2016-08-02 15:44
Possible duplicate of #287?

**Comment by sichvoge** [comment] 2016-08-02 15:51
It seems it is.

**Comment by nmarinel01** [comment] 2017-03-03 16:18
Closing on favor of #287

**Closed by nmarinel01** 2017-03-03 16:18 UTC
Labels: bug, major, ux
