### ISSUE TITLE
Issue in Try-It functionality

### ISSUE THREAD

**Issue by shantanu04** [mulesoft/api-console#234] opened 2016-03-07 14:53 UTC
Hi,

I have configured the api-console project for Single View mode. And trying to use the "Try-It" functionality. But I found that when I click on "Try-It" it shows the Authentication and Headers part but the Query Parameters and the GET, Clear and Reset buttons does not show up. And when I open the developer console for debugging, suddenly the Query Parameters along with the three buttons (i.e. GET, Clear and Reset buttons) show up. And after closing the developer console it again dissappears (I am using chrome browser).

Please find below screenshots:

![issue-before-dev-console](https://cloud.githubusercontent.com/assets/17704233/13572781/13c478aa-e4a2-11e5-8664-be28e8e297ef.PNG)

After opening developer console:

![issue-after-dev-console1](https://cloud.githubusercontent.com/assets/17704233/13572779/13b7d186-e4a2-11e5-845a-023b340d574f.PNG)

![issue-after-dev-console2](https://cloud.githubusercontent.com/assets/17704233/13572780/13bfc620-e4a2-11e5-87fd-fd6790685a4f.PNG)

I think there is some issue with the CSS. Can someone please help with this issue?

**Comment by carowright** [comment] 2018-02-22 18:15
Hi @shantanu04!
Sorry for the late response. I am closing this as I couldn't reproduce it in version 3.0.26. Feel free to reopen if applies.

**Closed by carowright** 2018-02-22 18:15 UTC
Labels: bug, major, v3
