### ISSUE TITLE
Render JSON schema to a more human friendly form

### ISSUE THREAD

**Issue by rajkumar1979** [mulesoft/api-console#113] opened 2015-03-03 22:20 UTC
Where are the RAML Files saved?

**Comment by ddossot** [comment] 2015-03-03 22:26
Anywhere, which is the beauty of it :+1: 

I personally serve my RAML files (and related JSON Schemas) over HTTP so I can access them easily from a central console deployed as a static site, something like:

    https://acme.com/raml-console/index.html?raml=https://service-a.acme.com/raml/v1/api.raml

**Comment by rajkumar1979** [comment] 2015-03-03 23:13
How do you document what is required and there are a few elements in a schema where one of them might be required , but you cannot send both of them as null.

How are they represented in RAML?

I was expecting that API Designer will convert the JSON schema into a html document that can be used by our customers,but it does not.

**Comment by ddossot** [comment] 2015-03-03 23:27
RAML represents resources, entity fields are represented in JSON or XML schema. Both schema types support optional and required fields.

I don't know about the API Designer. This is the API Console project. The API Console doesn't render the JSON schemas to HTML but it does syntax highlight them.

What type of HTML rendering were you thinking of? Something like https://github.com/mattyod/matic ?

I could see value in improving the way JSON schemas (and possibly XML schemas) are rendered in the console, especially when `$ref`s are used. In that case, what's visible in the console is incomplete, one has to manually browse to the `$ref`ed schemas.

Interestingly `matic` does dereference `$ref` when it creates the HTML rendering of the schema so that could indeed be a cool addition.

**Comment by rajkumar1979** [comment] 2015-03-03 23:34
#%RAML 0.8
title: Create Subscription
version: v2
#baseUri: http://corp.intuit.net
baseUri: http://mocksvc.mulesoft.com/mocks/efbc7958-6d0e-4687-b652-8668fbafdd0e
mediaType: application/json
/subscription:
  displayName: Subscription
  post:
   description: Create Subscription API
   headers:
      Accept:
        description:
          desc -- do we really need this to be required
          throw error if not provided, or unsupported media type
        type: string
        required: true
        example: example
        
      Authorization:
        description:
          desc
          throw error if not provided
        type: string
        required: true
        example: Intuit_IAM_Authentication intuit_token_type="IAM-Ticket",intuit_realmid="50000003",intuit_appid="Intuit.cto.api.gateway.simulator.test",intuit_token="V1-65-Q3y8elbiw74j5wdna2cei5",intuit_userid="100186433"

      Content-Type:
        description:
          here is the description
          throw error if not provided
        type: string
        required: true
        example: application/json; charset=utf-8
      
      User-Agent:
        description:
          des
        type: string
        required: false
        example: curl/7.30.0
      
      intuit_originatingip:
        description: des
          throw error if not provided
        type: string
        required: true
        example: 100.100.10.1
        
      intuit_webs_transaction_datetime:
        description: des
          in prod, set to current date time
          
          in pre-prod and the time-based testing flag is set to true, propagate date time if passed in, otherwise set to current date time
          
          in pre-prod with time-based testing flag set to false, set to current date time
        type: string
        required: false
        example: sss
          
      intuit_locale:
        description: 
          Here is the description for the header. 
          throw error if not provided
        type: string 
        required: true
        minLength: 5
        maxLength: 5
        example: en_US
        
      intuit_tid:
        description:
          desc
          throw error if not provided
        type: string
        required: true
        example: gw-7f501242-b7ab-43e7-a862-93027855347f
              
      intuit_assetalias:
        description: desc
          throw error if not provided
        type:  string
        required: true
        example: Intuit.cto.gateway-fabric.8
        
      intuit_assetid:
        description: desc
          throw error if not provided
        type: integer
        required: true
        example: 5189290262823711479
   body: 
    text/json:
     example: |
                               {
                                          "customerAccount": {
                                              "realmID": "123145631722297",
                                              "personaID": "123145631723942"
                                          },
                                          "offerID": "20000000",
                                          "paymentDetails": {
                                              "type": "CreditCard",
                                              "attribute": [
                                                  {
                                                      "name": "nameOnCard",
                                                      "value": "John"
                                                  },
                                                  {
                                                      "name": "cardNumber",
                                                      "value": "9919930747642032"
                                                  },
                                                  {
                                                      "name": "expirationMonth",
                                                      "value": "11"
                                                  },
                                                  {
                                                      "name": "expirationYear",
                                                      "value": "2015"
                                                  },
                                                  {
                                                      "name": "cvn",
                                                      "value": "123"
                                                  }
                                              ],
                                              "paymentAddress": {
                                                  "addressLine1": "123 main str",
                                                  "addressLine2": "APT 122",
                                                  "addressLine3": "Near Macdonald",
                                                  "addressLine4": "OPP Gas station",
                                                  "city": "San Diego",
                                                  "stateOrProvince": "CA",
                                                  "postalCode": "92122",
                                                  "country": "US"
                                              }
                                          }
                                      }
     schema: |
                       {
                            "$schema": "http://json-schema.org/draft-04/schema",
                            "type": "object",
                            "properties": {
                                "customerAccount": {
                                    "type": "object",
                                    "properties": {
                                        "personaID": {
                                            "type": "string",
                                            "description": "This is the standard Intuit company identifier - it is the same as the customerAccountID."
                                        },
                                        "authID": {
                                            "type": "string"
                                        },
                                        "realmID": {
                                            "type": "string"
                                        },
                                        "taxExemptionID": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "personaID",
                                        "realmID"
                                    ]
                                },
                                "offerID": {
                                    "type": "string"
                                },
                                "paymentDetails": {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string"
                                        },
                                        "attribute": {
                                            "type": "array",
                                            "items": [
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "name": {
                                                            "type": "string"
                                                        },
                                                        "value": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "paymentAddress": {
                                            "type": "object",
                                            "properties": {
                                                "addressLine1": {
                                                    "type": "string"
                                                },
                                                "addressLine2": {
                                                    "type": "string"
                                                },
                                                "addressLine3": {
                                                    "type": "string"
                                                },
                                                "addressLine4": {
                                                    "type": "string"
                                                },
                                                "city": {
                                                    "type": "string"
                                                },
                                                "stateOrProvince": {
                                                    "type": "string"
                                                },
                                                "postalCode": {
                                                    "type": "string"
                                                },
                                                "country": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }

**Comment by rajkumar1979** [comment] 2015-03-03 23:36
This my RAML file,
When I do a POST it says cannot parse JSON, but the JSON is a valid JSON, the error message is cannot parse the request.

{
  "error": "Could not parse body of type 'text/json'"
}

**Comment by ddossot** [comment] 2015-03-03 23:52
This issue doesn't seem related to the API Console, or is it? It doesn't even seem related to the current issue...

What is "it" in this sentence: "it says cannot parse JSON"? Your API server?

**Comment by ddossot** [comment] 2015-03-03 23:53
Also could you reformat your above comment, it's totally unreadable.

**Comment by rajkumar1979** [comment] 2015-03-04 00:02
lets forget about the error.

Lets talk about the HTML rendered by the API Designer.

I was expecting that the API Designer would format the JSON schema into a more readable format in a hierarchical structure, but it displays the JSON schema in a text box.

It does not look user friendly to me.

**Comment by ddossot** [comment] 2015-03-04 00:04
Cool, OK.

Then maybe you want to rename this issue to "Render JSON schema to a more human friendly form", or something like that? I think it's worth tracking this suggestion of yours.

**Comment by rajkumar1979** [comment] 2015-03-04 00:07
I have another issue , not sure is this is an error related to API Designer, do you want me to file a different ticket.

**Comment by ddossot** [comment] 2015-03-04 00:59
Please do file different issues in different tickets, yes, thanks.

**Comment by andyevans** [comment] 2015-06-15 23:42
+1 for this functionality - i think this is a duplicate of https://github.com/mulesoft/api-console/issues/82

**Comment by aquamatthias** [comment] 2015-09-29 13:46
+1

**Comment by usarid** [comment] 2015-09-29 14:16
This is coming, as a graphical tree viewer and as JSON schema expressed in YAML and as a much more streamlined schema expression capability... in a few weeks, within RAML 1, and in the tooling too.

**Comment by jarrodek** [comment] 2020-01-16 21:31
This was fixed in version 5

**Closed by jarrodek** 2020-01-16 21:31 UTC
Labels: enhancement, ux, v4
