### ISSUE TITLE
queryParameters patterns not correcly evaluated in console

### ISSUE THREAD

**Issue by lcapalbo-colpix** [mulesoft/api-console#211] opened 2016-01-06 20:18 UTC
I'm having an issue when using patterns to validate queryParameters.
When I run my project, I get a 400 (message: Bad Request) for wrong values, and 200 Ok for valid values. However, using Try it! in API console flags the values as invalid, so I need to click on Force.. My regexs work fine when consumig the api, I tested them on https://regex101.com/#javascript too..

See this little project for example:
[patternsNotWorking.zip](https://github.com/mulesoft/api-console/files/80306/patternsNotWorking.zip)

Am I doing something wrong?

**Comment by tehcyx** [comment] 2016-09-23 12:03
Hey, I would want to piggy back on that issue, as we're also facing trouble with the patterns for parameters. For example we have this pattern: "required, string matching [a-z][a-z0-9]+, 3-16 characters" but I will receive no error for putting a string like 123abc, however if it's too short or too long it will give me an error.

**Comment by lcapalbo-colpix** [comment] 2016-09-23 13:25
Can you try with ^[a-z][a-z0-9]+$  that is, add ^ and $ to you regex. 
I think 123abc matches the regex you are using because of the abc part

**Comment by tehcyx** [comment] 2016-09-23 13:53
We're even having a more complicated one, that is not working:
`^(((type:\u0028((blog|question|discussion|review)[,]?){1,4}\u0029){0,1})(\u0020subType:\u0028((featured_blog|featured_discussion|answered_question|unanswered_question|featured_question)[,]?){1,4}\u0029){0,1}){0,1}$`

which in that case has the ^ and $ sign enclosing the regex.

A valid match for that one would be:
`type:(blog)`
or
`type:(blog) subType:(featured_blog)`

See the regex working here: http://rubular.com/r/kdtyWDhXnh

**Comment by sichvoge** [comment] 2017-06-26 11:02
I think the console does that actually. I can't reproduce as you can see in the image below. Closing this. If it still a problem, please feel free to open it again.

![image](https://user-images.githubusercontent.com/498114/27536478-45b38b4e-5a67-11e7-9c0e-380853fa0a9c.png)

**Closed by sichvoge** 2017-06-26 11:02 UTC
Labels: bug, minor, need to verify
