### ISSUE TITLE
Nested traits from library loose namespace

### ISSUE THREAD

**Issue by eNcacz** [mulesoft/api-console#611] opened 2019-04-26 16:36 UTC
I have two traits in library, one trait use the another one and both are using some type from the same library:
```raml
#%RAML 1.0 Library

traits:
  ServerError:
    responses:
      500:
        description: This is 500 error.
        body:
          application/json:
            type: ErrorHolder

  BusinessError:
    is:
      - ServerError
    responses:
      400:
        description: This is 400 error.
        body:
          application/json:
            type: ErrorHolder

types:
  ErrorHolder:
    type: object
    properties:
      errors:
        type: object[]
        required: false
      idCall:
        type: string
        required: false
```
I have stored this content in `lib.raml` file.

Now I have another raml file which uses this library:

```raml
#%RAML 1.0
title: Example
version: 1.0

uses:
  lib: lib.raml

/foo:
  get:
    is:
      - lib.BusinessError
```

When I generate documentation via api-console-cli version 1.0.13, then the 400 response is rendered properly:
![image](https://user-images.githubusercontent.com/15668267/56822193-9a7bfc80-6850-11e9-8b1a-cf4938429c20.png)

but the 500 response has no properties defined:
![image](https://user-images.githubusercontent.com/15668267/56822218-aa93dc00-6850-11e9-8b51-bf77249fd018.png)

I expect that both responses will look the same.

I have found three dirty workarounds:

1. Reference both traits from the endpoint. Library is still the same but api definition will change in this way (only the changed part is here for better readability):

```raml
/foo:
  get:
    is:
      - lib.ServerError
      - lib.BusinessError
```

2. Keep the api definition as is and "guess" the use prefix in the library :

```raml
  BusinessError:
    is:
      - lib.ServerError
    responses:
      400:
        description: This is 400 error.
        body:
          application/json:
            type: ErrorHolder
```

3. This is similar to point 2 but I will use the guessed prefix before the type name:

```raml
  ServerError:
    responses:
      500:
        description: This is 500 error.
        body:
          application/json:
            type: lib.ErrorHolder
```

It is big surprise for me that points 2 and 3 works. I think it is a bug.
I understand why option 1 works but I think it should not be necessary to reference again the ServerError trait when it is already referenced by BusinessError trait.

**Comment by jarrodek** [comment] 2019-04-26 21:06
Hi,
Thanks for the issue report. It appears to be a problem with AMF parser that cannot be fixed with API Console. Could you please copy this ticket to AMF project? https://github.com/aml-org/amf/issues

I am closing this ticket as there's nothing I can do without changes in the data model.

**Closed by jarrodek** 2019-04-26 21:06 UTC

**Comment by jarrodek** [comment] 2019-04-26 21:15
Also, I asked our RAML specialist about this issue. It appears that this example is invalid.
According to the spec a trait can only be applied to a method or a resource type. Or in other word, trait cannot be applied to another trait. The right approach here is to create a resource type that has both responses definition.

**Comment by vsigler** [comment] 2019-04-27 09:41
Interesting. In that case I would expect a validation error if I use ```is``` in a trait definition.
I would also expect the spec to state this a bit more explicitly. Stating that it can be applied to methods and resource types is not the same as that it cannot be applied to traits.

> A trait, like a method, can provide method-level nodes such as description, headers, query string parameters, and responses.

**Comment by eNcacz** [comment] 2019-04-30 15:39
> The right approach here is to create a resource type that has both responses definition.

Thanks for this information but it also does not work. I will report it to the amf project.

**Comment by eNcacz** [comment] 2019-04-30 16:52
Sorry, I'm not sure what I need to report to the amf project.
I have simplified the example, removed the trait hierarchy and created the resourceType:

lib.raml:
```raml
#%RAML 1.0 Library

traits:
  ServerError:
    responses:
      500:
        description: This is 500 error.
        body:
          application/json:
            type: ErrorHolder

types:
  ErrorHolder:
    type: object
    properties:
      errors:
        type: object[]

resourceTypes:
  fooendpoint:
    get:
      is:
        - ServerError
```
api.raml:
```raml
#%RAML 1.0
title: Example
version: 1.0

uses:
  lib: lib.raml

/foo:
  type: lib.fooendpoint
```
The `errors` attribute does not appears in the generated documentation of the `/foo` endpoint.
But if I change the 
```raml
      is:
        - ServerError
```
sequence in the lib.raml to 
```raml
      is:
        - lib.ServerError
```
then the `errors` attribute appears in the generated documentation as expected.

So I have run `java -jar /tmp/amf/amf-4.1.0-SNAPSHOT.jar parse -in "RAML 1.0" -mime-in "application/yaml" api.raml >api.json` for both versions of my lib.raml and compare the results.
Results are almost the same - there is only one difference on one line - see [amf-output.zip](https://github.com/mulesoft/api-console/files/3132212/amf-output.zip)

If I compare the api-model.json file produced by api-console for both cases, then there is much more differences: 
[api-console-output.zip](https://github.com/mulesoft/api-console/files/3132218/api-console-output.zip)

I do not understand what is the problem in the AMF (what is the expected output from AMF) so I'm not able to report it properly.
Could you help me to describe the problem properly from the AMF point of view?

**Comment by jarrodek** [comment] 2019-05-16 23:32
Hi,
Sorry for the late response. I was on vacations.

The example you provided in the last comment is valid. However the problem is with how AMF resolves types. So in context of an API `lib.ServerError` is valid but it shouldn't be. The library (as a sharable fragment) should not assume any name that will be used when applying the library. Therefore `is: ServerError` should work and ` is: lib.ServerError` should render an error.The library itself (as a fragment) don't have `lib` defined anywhere.

**Comment by eNcacz** [comment] 2019-05-17 06:36
> Sorry for the late response. I was on vacations.

That's OK. Welcome back :-)

I agree with your response. 
The first variant `is: [ServerError]` should work but it doesn't. Is it still an error in amf or is it error in api console?

I'm ready to report it to amf project but I do not know what is the expected output from amf so I worry that I'm not able to describe the error properly in amf issue report.

**Comment by jarrodek** [comment] 2019-05-17 08:23
@eNcacz I will report the issue to the AMF team tomorrow for you. It might be easier to process this issue. However I initially discussed this issue with AMF team member and apparently it is how the parser processes the data at the moment. This means it might take drive effort to correct the behavior. Anyway, hopefully soon we will fix it.

**Comment by eNcacz** [comment] 2019-05-17 08:25
@jarrodek Great, thank you very much.

**Comment by jarrodek** [comment] 2019-05-17 16:29
@eNcacz I've created an issue in AMF project. See referenced issue.
