### ISSUE TITLE
The order of query parameters should be preserved

### ISSUE THREAD

**Issue by ddossot** [mulesoft/api-console#99] opened 2015-01-30 18:34 UTC
The query parameters are getting alphabetically re-ordered, which can be damaging.

Consider the case when the RAML spec defines the following query params:

```
from:
to:
offset:
limit:
```

There is a logic in their ordering: for an end user, seeing `from` next to `to` is helpful information. Having to scroll down to find out that both params exist after being alpha re-ordered is counter-productive.

**Comment by usarid** [comment] 2015-01-31 02:28
+1 -- agree completely, we need to fix our parsers to preserve such order
of sibling properties, and we need to make sure RAML 1.0 formalizes that
need.

**Comment by mgogov** [comment] 2015-02-04 14:44
+1

**Comment by shravanak** [comment] 2015-03-26 20:40
+1

**Comment by janadeau** [comment] 2015-04-20 14:50
+1

**Comment by tonyleigh** [comment] 2015-04-29 16:04
+1

**Comment by blakeembrey** [comment] 2015-05-07 18:58
Hi everyone! The patch for this was released in the JS RAML parser last week with `0.8.11` (https://github.com/raml-org/raml-js-parser/pull/141). Once we update the parser version, all resources should start resolving in the correct order. /cc @jcenturion

**Comment by sichvoge** [comment] 2016-07-28 16:48
The current parser seems to preserve ordering (see image output working with the parser)

**Comment by lukasgeiter** [comment] 2017-01-09 21:52
The problem is that query parameters, type properties and similar lists are all stored as JavaScript objects which have no particular order. To preserve ordering, this data would have to be stored using arrays.

**Comment by Skorpyon** [comment] 2017-03-09 19:34
Any updates?
Api-console sort alfabetical ALL prorerties in DataTypes, queryParameters and everywhere
Is is ugly.

**Comment by sichvoge** [comment] 2017-03-23 16:49
Is this still happening? Can't reproduce it with the example above.

**Comment by carowright** [comment] 2017-05-19 13:06
Fix available in [v3.0.17](https://github.com/mulesoft/api-console/releases/tag/v3.0.17)

**Closed by carowright** 2017-05-19 13:06 UTC
Labels: bug, major, raml1.0

**Comment by lukasgeiter** [comment] 2017-05-19 19:17
@sichvoge since this issue is closed now, is there a separate issue that tracks the progress on fixing the ordering of type properties?

**Comment by sichvoge** [comment] 2017-05-22 12:57
Is that not fixed with this?

**Comment by lukasgeiter** [comment] 2017-05-22 13:31
It doesn't seem like it. I downloaded the release and tested with the build in `dist`. With this RAML, properties displayed in *Types* are in the order **a, b** instead of **b, a**

```
#%RAML 1.0
title: Property Ordering Test

types:
  Foo:
    type: object
    properties:
      b: string
      a: string
```
