### ISSUE TITLE
The browser console will output non-unique id error

### ISSUE THREAD

**Issue by lanmolsz** [mulesoft/api-console#551] opened 2017-12-26 04:16 UTC
The errors caused by these components：
- `auth-methods`
    - `auth-method-basic.html` line 67
- `paper-input`
    - `paper-input.html` line 125
- `raml-request-url-editor`
    - `raml-request-url-editor.html` line 163

Can solve it?

**Comment by jarrodek** [comment] 2017-12-27 13:27
This is Polymer's paper-input issue. Others can be fixed.

**Comment by lanmolsz** [comment] 2018-01-02 14:24
@jarrodek Because the parameters are repeated

**Comment by jarrodek** [comment] 2018-01-08 15:27
Even in ARC elements the error is caused by Polymer's `iron-input` element. The best workaround is to use the following code on the page source (before loading elements and polyfills):

```javascript
<script>
    /* this script must run before Polymer is imported */
    window.Polymer = {
      dom: 'shadow'
    };
  </script>
```
This will force Chrome to use shadow DOM which encapsulate the elements and therefore ID conflicts won't happen.

I am not sure if Chrome team is planning to update 1.x.x version of the `iron-input`. I am planing to move the elements to version 3.x.x once it's released so probably it will be fixed there.

**Comment by jarrodek** [comment] 2018-02-28 18:09
There's a plan to upgrade the elements to Polymer v3 which should not have this issue in the future.
However upgrade will take a time (weeks probably) so it's nothing I can fix fast.

**Comment by jarrodek** [comment] 2019-08-22 04:43
This issue is fixed in upcoming 6.0.0 release

**Closed by jarrodek** 2019-08-22 04:43 UTC
Labels: v4
