### ISSUE TITLE
Default queryParameter values are not send in tryIt unless modified

### ISSUE THREAD

**Issue by agustinlg** [mulesoft/api-console#501] opened 2017-07-13 19:31 UTC
```
#%RAML 1.0
title: Default example test

/some:
  get:
    queryParameters: 
      some:
        type: string
        example: some
        required: true
    responses: 
      200:
        body: 
          application/json:
            example: {"some" : "some"}
```

**Comment by jarrodek** [comment] 2017-07-13 19:33
Duplicate of #484

**Comment by jarrodek** [comment] 2017-07-17 15:23
Although the issue is fixed in main branch, I still have to update the Anypoint branch. It should be fixed in an hour or so.

**Comment by jarrodek** [comment] 2017-07-18 17:11
This has been fixed already.

**Closed by jarrodek** 2017-07-18 17:11 UTC
Labels: bug, v4
