### ISSUE TITLE
Regression for chrome browser.

### ISSUE THREAD

**Issue by JaniszM** [mulesoft/api-console#198] opened 2015-12-03 12:24 UTC
Test "should be able to cache credentials between resources" seems to fail on chrome browser.

**Comment by mseashor** [comment] 2015-12-03 18:32
I know there was an issue fixed in the travis.yml which gave a larger
screen size (1280x1024) and it would fail if the browser size was too small
- basically because it would look for things not shown on the screen.

Can you try manually increasing the size of the browser to at least
1280x1024 (to match Travis CI size) at the beginning of the test run?  That
will help narrowing down if it's a problem that was seen before that's not
fully worked around or if it's a new issue.

**Comment by mseashor** [comment] 2015-12-03 23:51
FYI - I confirmed that if you change 'browserName' to 'chrome' in test/regression/local.protractor.conf.js - I see the issue.  

It appears that the default width for Chrome is less than the default width for Firefox (testing on Mac OSX) and it's small enough that the 'credentials' section is collapsed and not visible so the test fails.  Manually widening it works, but is obviously not ideal.
 
I'm thinking it's not a bad idea to explicitly size the browser to create a more deterministic test, but I'll default to someone who really knows the code to recommend an approach (@jcenturion?).

Here's a quick change which shows a potential fix, but maybe there's a better place to do it globally or cleaner, etc.

Modify test/regression/standalone/directiveSpec.js to add the "browser.manage()..." line below. grunt regression passes with chrome if I do this below.

````
'use strict';

var assertions = require('../assertions');

module.exports = function() {
  browser.manage().window().setSize(1280,1024);

  it('should be able to diplay the API title', function () {
    // Arrange
    var assert = assertions.create('resource');
    ...
````

**Comment by JaniszM** [comment] 2015-12-04 08:30
Confirm, I launched it on OSX chrome.

**Comment by carowright** [comment] 2018-03-05 20:14
Hi all! 
I am closing this as the tests are now running on chrome for the latest version 3.0.26.

**Closed by carowright** 2018-03-05 20:14 UTC
Labels: bug, minor, v3
