### ISSUE TITLE
Did examples fully supported?

### ISSUE THREAD

**Issue by xinyifly** [mulesoft/api-console#226] opened 2016-02-25 13:19 UTC
If I use it, neither can display.

**Comment by sichvoge** [comment] 2016-07-28 13:14
Can you elaborate a bit more with an example on what the problem is that you face?

**Comment by nmarinel01** [comment] 2017-01-10 22:50
Hi @xinyifly !
Im closing this question, but please, feel free to reopen it if applies. 
Thanks and regards !

**Closed by nmarinel01** 2017-01-10 22:50 UTC
Labels: question
