### ISSUE TITLE
Try it body is blank

### ISSUE THREAD

**Issue by piti118** [mulesoft/api-console#529] opened 2017-09-12 14:35 UTC
Body for try it should be prefilled with example parsed from raml types. Right now, Try it button is essentially useless without prefilled body and there is no where on api-console that we can find prefilled example body.

## Expected outcome

Body for try it should be prefilled with example parsed from raml types.

## Actual outcome

![screen shot 2017-09-12 at 21 26 57](https://user-images.githubusercontent.com/591316/30331506-36697cba-9802-11e7-9b31-5d0e952a2099.png)

## Steps to reproduce

```
#%RAML 1.0
title: PINGME
version: v1
baseUri: http://localhost:4444/api/v1

protocols:
  - http

/ping:
  post:
    body:
      application/json:
        properties:
          msg:
            type: string
            examples:
              - hello
              - world
    responses:
      200:
        body:
          application/json:
            properties:
              message: 
                type: string
                example: hello
```

Then click try it and body tab. It's completely blank
## Was this working before?

- [ ] Yes, it was working before
- [ ] No, it was already broken
- [x] I don't know / not sure

## Affected browsers

- [x] All or I don't know
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer <\3
- [ ] Edge
- [ ] Safari
- [ ] Other (please, specify)

**Comment by jarrodek** [comment] 2017-09-13 17:19
This is working as intended. 
Examples that are defined for responses are in the documentation view. In the request panel view it accepts examples that are defined for the request, not the response.

Closing as WAI but feel free to comment.

**Comment by piti118** [comment] 2017-09-13 17:23
But I did have 
```
body:
      application/json:
        properties:
          msg:
            type: string
            examples:
              - hello
              - world
```

I expect at least
```
{
  "msg": "hello"
}
```
to be prefilled in the body.

**Comment by jarrodek** [comment] 2017-09-13 17:35
OK. It's more complicated then. Neither parser nor the expansion library have created the example property out of the properties list. This is actually quire challenging task because of complexity of `properties`. Though, it was done in a resource documentation viewer (type example viewer) so possibly it can be used again.

**Comment by piti118** [comment] 2017-09-13 17:39
The demo do have it though https://mulesoft.github.io/api-console/#/docs/resources-0-methods-0

<img width="1153" alt="screen shot 2017-09-14 at 00 38 44" src="https://user-images.githubusercontent.com/591316/30391851-1aa687fa-98e5-11e7-95de-54c3ac6e6cf4.png">

**Comment by jarrodek** [comment] 2017-09-13 18:12
That's right, but the example is defined for the body and not for properties that are in the body. That's different and the example has to be computed when opening the panel from the properties. So essentially right now I do not have this information to display and I have to compute it.

**Comment by jarrodek** [comment] 2019-12-12 22:11
This was fixed in v5 and it is also working in upcoming v6.

**Closed by jarrodek** 2019-12-12 22:11 UTC
Labels: enhancement, v4
