### ISSUE TITLE
Example facet is not fully supported 

### ISSUE THREAD

**Issue by tfayruzov** [mulesoft/api-console#389] opened 2017-01-05 17:26 UTC
[Single example](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#single-example) definition describes additional fields that can be set for an example, but those currently do not render in the console.

Repro RAML:
```
#%RAML 1.0
title: Example
version: v1
types:
  SimpleString:
    description: Description of a string type
    type: string
    example:
      displayName: Display name of a string example
      description: Description of a string example
      value: example string
/exampleRes:
  post:
    body:
      application/json:
        type: SimpleString
```

**Comment by nmarinel01** [comment] 2017-01-06 18:42
Hi @tfayruzov !
If you change "example" by "examples" all examples will be displayed at console. 
Hope this helps.
Regards
![image](https://cloud.githubusercontent.com/assets/19980188/21728721/773b2af4-d426-11e6-8f1e-156e67bbc3d8.png)

**Comment by tfayruzov** [comment] 2017-01-06 18:56
Thanks for looking into it. If I change example to `examples` it will treat `displayName`, `description` and `value` as separate examples, but that is not what I need. These are the fields that should describe a *single example*. Providing the spec link again: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#single-example. The table with facets there explains that each example can have it's own name and description, not only the example itself. I.e. I can have multiple examples, each with its own description, like:

```
types:
  SimpleString:
    description: Description of a string type
    type: string
    examples:
      example1:
        displayName: Display name of a string example
        description: Description of a string example
        value: example string
      example2:
        displayName: Display name of a string example
        description: Description of a string example
        value: example string
```

Hope that makes my question clearer, please let me know if you need a better elaboration.

**Comment by nmarinel01** [comment] 2017-01-10 13:43
Hi @tfayruzov ! I get the point now. Thanks for clarifying.
Regards

**Comment by sichvoge** [comment] 2017-03-23 16:04
Changed it to an enhancement request since its actually not a bug. We haven't really put it into the UI yet. That might be a very good candidate for the next version. 

@tfayruzov I changed your request, hope you don't mind.

**Comment by jarrodek** [comment] 2017-03-23 18:24
This works with the next API console.

**Comment by sichvoge** [comment] 2017-06-23 16:31
This is actually not fully supported. Although the values are correctly displayed this time, the additional facets like `description` or `displayName` are not considered.

**Comment by jarrodek** [comment] 2017-06-26 12:17
@sichvoge I may not understand what is this about but the examples in this notation works with new console. I remember working on that few months back

**Comment by sichvoge** [comment] 2017-06-26 13:22
This is what I currently see

![image](https://user-images.githubusercontent.com/498114/27541141-bd146858-5a7a-11e7-8d31-96c237779fd7.png)

The examples have additional description and displayName facets that are not rendered.

**Comment by jarrodek** [comment] 2017-06-26 13:57
Now I get it. Thanks.

**Comment by jarrodek** [comment] 2017-06-27 18:20
@sichvoge Can you share a raml with me here so I can take a look into it?

**Comment by sichvoge** [comment] 2017-06-28 05:38
I took the one from the OP.

**Comment by jarrodek** [comment] 2017-07-12 15:12
This was fixed in the component that renders types and new builds of the console are this issue free.
Just use API console build tools to rebuild the console or update bower if you are using the element.

**Closed by jarrodek** 2017-07-12 15:12 UTC
Labels: enhancement, raml1.0, v4, verified
