### ISSUE TITLE
API not showing rotes after update to 1.0.1

### ISSUE THREAD

**Issue by cavarzan** [mulesoft/api-console#576] opened 2018-06-29 17:24 UTC
Hi!

I recently used the API console for RAML 1.0 version build with the following command:

` api-console build -a api.raml -t "RAML 1.0" -n "5.0.0-preview"`

Using version `1.0.0` the build succeed and the api-console was displayed correctly.

After updating to 1.0.1, the api opens with an empty screen:
![image](https://user-images.githubusercontent.com/3915288/42105697-b6cc31ac-7ba7-11e8-8990-1a944f50b35e.png)

I've tried to rollback to 1.0.0 but the error persists. The raml file is ok, since I can build a static doc page using mattjtodd/raml2html dokcer image to generate html out of api.raml.

Any clues of what I'm missing?

## Was this working before?

- [x] Yes, it was working before
- [ ] No, it was already broken
- [ ] I don't know / not sure

## Affected browsers

- [x] All or I don't know
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer <\3
- [ ] Edge
- [ ] Safari
- [ ] Other (please, specify)

**Comment by jarrodek** [comment] 2018-06-29 22:00
Hi,

Thank you for issue report.
The tool caches downloaded API console sources to speed up the build. The 5.0.0-preview does not changing version since it's a preview branch. 
There was a breaking change to the code as the data model changed significantly but the build tool tries to use old source code.
Please, remove cache directory and this will start working again. Very soon the console will be released as a stable version and there will be no such problem.

## Cache location

**Windows**
%HOME%\AppData\api-console\cache\

**MacOS**
~/Library/Preferences/api-console/cache/

**Linux**
~/.config/api-console/cache/
 
After removing the folder and rebuilding the console it will work.
Sorry for this issue.

**Comment by cavarzan** [comment] 2018-06-30 18:42
@jarrodek thanks for the feedback!

I removed the folder, but now the build has an error:

```
error: Unable to find suitable version for iron-meta
error: iron-meta: Unable to find suitable version for iron-meta
    at createError (/Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/util/createError.js:4:15)
    at Manager._electSuitable (/Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/core/Manager.js:1002:15)
    at /Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/core/Manager.js:735:22
    at _fulfilled (/Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:816:13)
    at /Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:570:49
    at runSingle (/Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/Users/deividi/.nvm/versions/node/v8.9.1/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
error:  
```

I try to change the node version & reinstall api-console and deleting api-console folder doesn't solve it.

**Comment by jarrodek** [comment] 2018-06-30 22:11
OK, I can confirm the error:
```
jarrod@PawelPsztycPc:~$ api-console build --verbose
  Building the API console. This may take a moment.
info: Build cache hash e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
info: Setting builds cache path to  /home/jarrod/.config/api-console/cache/builds
info: Preparing build process...
info: Creating working directory...
info: Working directory created:  /tmp/tmp-598hWqqz3gTSzvG
info: Setting sources cache path to  /home/jarrod/.config/api-console/cache/sources
info: Downloading latest release info...
info: Checking for cached console in  /home/jarrod/.config/api-console/cache/sources/5.0.0-preview.zip
info: Cached version exists!
info: Reusing cached console sources...
info: Zip file has been extracted.
info: Installing bower dependencies...
info: Dependencies installed.
info: Installing additional bower dependencies...
info: Installing:  0=advanced-rest-client/oauth-authorization#^2.0.0, 1=advanced-rest-client/cryptojs-lib, 2=advanced-rest-client/arc-polyfills, 3=advanced-rest-client/xhr-simple-request#^2.0.0, 4=web-animations/web-animations-js#^2.3
error:
error: Unable to find suitable version for iron-meta
error: iron-meta: Unable to find suitable version for iron-meta
    at createError (/usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/util/createError.js:4:15)
    at Manager._electSuitable (/usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/core/Manager.js:1002:15)
    at /usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/core/Manager.js:735:22
    at _fulfilled (/usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:816:13)
    at /usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:570:49
    at runSingle (/usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/api-console-cli/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
error:
info: Cleaning up temporaty dir...
info: Removing  /tmp/tmp-598hWqqz3gTSzvG
```'
I will take care of it later today. Thank you for the information.

**Comment by jarrodek** [comment] 2018-07-02 00:28
The problem is now resolved.

It turns out that for last 3 days the `5.0.0-preview` tag was created on the master branch which contains version 4. of the console. Now, when bower tried to install dependencies from version 5 it was trying to upgrade old components which are incompatible. Hence error.
I restored the tag and now it works perfectly.

**Closed by jarrodek** 2018-07-02 00:28 UTC

**Comment by cavarzan** [comment] 2018-07-02 17:00
Working fine! Thanks
