### ISSUE TITLE
Errors are not shown in UI (only in browser console)

### ISSUE THREAD

**Issue by alvassin** [mulesoft/api-console#413] opened 2017-03-25 15:03 UTC
When loading invalid RAML, nothing happens in UI. In browser console i see the following:

```
[xmldom error]	invalid doc source 
@#[line:0,col:undefined]
error @ api-console-vendor.js:1328

api-console-vendor.js:49681 SyntaxError: Expected "(" or name but "{" found.
    at a (api-console-vendor.js:1350)
    at Object.n [as parse] (api-console-vendor.js:1350)
    at Object.l [as parse] (api-console-vendor.js:1348)
    at Object.a [as parse] (api-console-vendor.js:1347)
    at e.patchType (api-console-vendor.js:1319)
    at e.patchReferences (api-console-vendor.js:1319)
    at e.patchReferences (api-console-vendor.js:1319)
    at e.patchReferences (api-console-vendor.js:1319)
    at e.patchReferences (api-console-vendor.js:1319)
    at e.patchReferences (api-console-vendor.js:1319)
```

Could you please display such messages in UI?

**Comment by nmarinel01** [comment] 2017-04-05 18:47
Hi @alvassin ,
thanks for your suggestion. I understand this is a duplicate of #314, which was included at latest Console release (3.0.16). Now we have UI feedback for errors that looks like this:
![image](https://cloud.githubusercontent.com/assets/19980188/24721526/053ccd86-1a17-11e7-974c-c6201128498a.png)


So Im closing this report, but please, feel free to reopen or to create a new one if applies.
Regards!

**Closed by nmarinel01** 2017-04-05 18:47 UTC
