### ISSUE TITLE
broken field ordering in big objects

### ISSUE THREAD

**Issue by nektru** [mulesoft/api-console#493] opened 2017-06-30 17:53 UTC
I makes raml like this:
```
#%RAML 1.0
title: Test field order

types:
  C:
    type: object
    properties:
      A: string
      B: string
      C: string
      D: string
      E: string
      F: string
      J: string
      K: string
      L: string
      M: string
```
api-console 4.0 displays fields in a mixed order:
```
{
  "L": "string",
  "M": "string",
  "A": "string",
  "F": "string",
  "D": "string",
  "B": "string",
  "J": "string",
  "C": "string",
  "E": "string",
  "K": "string"
}
```
This problem affects objects with a number of properties, greater than nine.
If remove one of this properties - order will be normal.

**Comment by jarrodek** [comment] 2017-07-12 15:08
Hi,

Thank you for the issue report. The console doesn't sort any data anywhere. If any data are processed then it can be either in the parser, expansion library or raml2obj. This has to be investigated.

**Comment by jarrodek** [comment] 2017-07-17 18:10
This is relatively easy fix. 

The problem is however in JavaScript object and parser output. So the RAML parser parses properties to a map (`Object`) which do not guarantee ordering. Because of that when iterating over a map it will be done in some arbitrary order. I'm not conferable with sorting any data in the console. But however it won't going to be order defined in RAML anyway so there's no harm here and simple sort function when iterating over keys won't cause any damage (well, not more damage).

**Comment by jarrodek** [comment] 2017-07-17 20:12
Fixed by: https://github.com/advanced-rest-client/raml-behaviors/commit/70fbad4defdcf78279e7742557089b8523856e89

**Closed by jarrodek** 2017-07-17 20:12 UTC
Labels: need to verify

**Comment by sichvoge** [comment] 2017-07-18 11:20
@jarrodek did you file this as a bug in the parser? In RAML, the order must be preserved by all means.

**Comment by jarrodek** [comment] 2017-07-18 11:24
It is not a parser problem. Kind of. You can't preserve order in a
JavaScript object. You have to use arrays for ordered lists. So even if the
parser preserves order architectonically it was a mistake to produce json
output of those lists as an object.
