### ISSUE TITLE
Type extending inside response has no effect

### ISSUE THREAD

**Issue by zeromodule** [mulesoft/api-console#463] opened 2017-06-02 16:39 UTC
types:
      MyType:
        properties: 
          a: string
          b: string
    /resource:
      get:
        responses:
          200:
            body:
              application/json:
                type: MyType
                properties:
                  c: string              

Result:
![screenshot_2](https://cloud.githubusercontent.com/assets/5268937/26735329/26fce830-47ca-11e7-8c21-c6cef7655fc5.png)

**Comment by sichvoge** [comment] 2017-06-02 17:01
This seems to work:

```yaml
#%RAML 1.0
title: Test

types:
  MyType:
    properties: 
      a: string
      b: string
  Extended:
    type: MyType
    properties:
      c: string
/resource:
  get:
    responses:
      200:
        body:
          application/json:
            type: Extended
```

But yes, that seems to be a bug.

**Comment by zeromodule** [comment] 2017-06-02 17:13
@sichvoge yes, I solved this problem just like you :)

**Comment by jarrodek** [comment] 2017-07-04 11:56
In v3 and v4 this problem is caused by [raml2obj](https://github.com/raml2html/raml2obj) module.
V4 uses fork of this module where this issue has been fixed.

Fixed by 
* https://github.com/advanced-rest-client/raml-json-enhance/commit/5d43ebe62f13b8199184a4f2750bce220a11cafe
* https://github.com/advanced-rest-client/raml2obj/commit/45b0405e03418301f81dbca68f8e5d820196f610

**Closed by jarrodek** 2017-07-04 11:56 UTC
Labels: bug, raml1.0, v4, verified

**Comment by jarrodek** [comment] 2017-07-04 12:28
For this issue to work in `api-console-cli` an update of the CLI tool is required.
